ALTER TABLE IF EXISTS user_settings DROP COLUMN IF EXISTS auto_sync_enabled;

ALTER TABLE IF EXISTS group_members ADD COLUMN IF NOT EXISTS active BOOLEAN;
UPDATE group_members SET active = TRUE WHERE active IS NULL;
ALTER TABLE IF EXISTS group_members ALTER COLUMN active SET DEFAULT TRUE;
ALTER TABLE IF EXISTS group_members ALTER COLUMN active SET NOT NULL;

ALTER TABLE IF EXISTS group_members ADD COLUMN IF NOT EXISTS left_at TIMESTAMP WITH TIME ZONE;
