ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS users ALTER COLUMN deleted SET DEFAULT FALSE;
ALTER TABLE IF EXISTS users ALTER COLUMN deleted SET NOT NULL;
