ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS users ALTER COLUMN deleted SET DEFAULT FALSE;
ALTER TABLE IF EXISTS users ALTER COLUMN deleted SET NOT NULL;
ALTER TABLE IF EXISTS user_settings DROP COLUMN IF EXISTS auto_sync_enabled;
